export const dummyPosts = [
  {
    id: '1',
    user: { id: '101', nickname: '푸른고래' },
    images: ['https://source.unsplash.com/random/1'],
    title: 'My First Post',
    content: `안녕하세요, 이번에 처음으로 임시보호를 해보게 된 예비 임보자입니다. 아직 많이 부족하지만 용기를 내어 아이를 맞이하기로 결심했어요.<br/>
이번에 퍼디 매칭을 통해 한 달 정도 보호할 강아지를 데려올 예정인데요, 막상 준비를 하려니 어떤 것부터 챙겨야 할지 막막해서 이렇게 글을 남깁니다.<br/>
혹시 임보 경험이 있으신 분들께 몇 가지 여쭤보고 싶어요.<br/>
집에 처음 들어올 때 강아지가 덜 불안해할 수 있도록 어떤 환경을 만들어주면 좋을까요?<br/>
꼭 사야 하는 기본 용품이나 준비물이 있을까요?<br/>
처음 며칠 동안 특히 조심해야 할 점이 있다면 알려주세요.<br/>
혹시 아이와 조금이라도 빨리 친해질 수 있는 팁이 있을까요?<br/>
주변에서 다들 “처음엔 낯설어할 거야”라고 말씀하시는데, 제가 더 긴장하고 있나 봅니다.<br/>
잘 해주고 싶은 마음이 커서 걱정도 많네요.<br/>
선배 임보자님들의 경험이나 작은 팁이라도 정말 큰 도움이 될 것 같아요. 읽어주셔서 감사합니다. 많은 조언 부탁드립니다! 🥹`,
    likes: 5,
    views: 34,
    created_at: '2025-07-21T10:15:00Z',
  },
  {
    id: '2',
    user: { id: '102', nickname: '푸른래' },
    images: [],
    title: 'Summer Vibes',
    content: 'Loving the summer weather lately ☀️',
    likes: 12,
    views: 78,
    created_at: '2025-07-22T14:30:00Z',
  },
  {
    id: '3',
    user: { id: '103', nickname: 'ss래' },
    images: ['https://source.unsplash.com/random/3'],
    title: 'My Dog Max',
    content: "Here's a picture of my dog Max at the park.",
    likes: 20,
    views: 112,
    created_at: '2025-07-23T09:05:00Z',
  },
  {
    id: '4',
    user: { id: '104', nickname: 'dd' },
    images: ['https://source.unsplash.com/random/4'],
    title: 'New Coffee Place',
    content: 'Just discovered this amazing café downtown!',
    likes: 9,
    views: 54,
    created_at: '2025-07-24T18:40:00Z',
  },
  {
    id: '5',
    user: { id: '105', nickname: 'dㅇ' },
    images: [],
    title: 'Looking for Book Recommendations',
    content: 'What’s a good novel to read these days?',
    likes: 2,
    views: 26,
    created_at: '2025-07-25T08:22:00Z',
  },
  {
    id: '6',
    user: { id: '106', nickname: '푸른고ㄶ래' },
    images: ['https://source.unsplash.com/random/6'],
    title: 'My Artwork 🎨',
    content: 'Sharing one of my recent paintings.',
    likes: 17,
    views: 94,
    created_at: '2025-07-26T13:55:00Z',
  },
  {
    id: '7',
    user: { id: '101', nickname: '푸른고래' },
    images: ['https://source.unsplash.com/random/7'],
    title: 'Weekend Hike',
    content: 'Went hiking in the mountains. Nature is healing.',
    likes: 15,
    views: 88,
    created_at: '2025-07-27T16:00:00Z',
  },
  {
    id: '8',
    user: { id: '101', nickname: '푸른고래' },
    images: [],
    title: 'Question About React',
    content: 'How do I handle state across multiple components?',
    likes: 3,
    views: 42,
    created_at: '2025-07-28T11:12:00Z',
  },
  {
    id: '9',
    user: { id: '101', nickname: '푸른고래' },
    images: ['https://source.unsplash.com/random/9'],
    title: 'City Lights',
    content: 'Captured this shot last night. Love the city glow.',
    likes: 22,
    views: 130,
    created_at: '2025-07-29T21:47:00Z',
  },
  {
    id: '10',
    user: { id: '111', nickname: 'ㅇㅇ' },
    images: ['https://source.unsplash.com/random/10'],
    title: 'Trying Out Tailwind CSS',
    content: 'Built a page with Tailwind today. Super clean and fast.',
    likes: 6,
    views: 48,
    created_at: '2025-07-30T07:30:00Z',
  },
  {
    id: '11',
    user: { id: '141', nickname: 'ㅇㄴㅁㄴ' },
    images: ['https://source.unsplash.com/random/9'],
    title: 'City Lights',
    content: 'Captured this shot last night. Love the city glow.',
    likes: 22,
    views: 130,
    created_at: '2025-07-29T21:47:00Z',
  },
  {
    id: '12',
    user: { id: '107', nickname: 'ㅓㅓ' },
    images: ['https://source.unsplash.com/random/10'],
    title: 'Trying Out Tailwind CSS',
    content: 'Built a page with Tailwind today. Super clean and fast.',
    likes: 6,
    views: 48,
    created_at: '2025-07-30T07:30:00Z',
  },
];

export const dummyComments = [
  // 게시물 1번
  {
    id: '1',
    parent_id: null,
    post_id: '1',
    reply_comments: [
      {
        id: '2',
        parent_id: '1',
        post_id: '1',
        user: { id: '121', nickname: 'ㄴㄴㅁ' },
        content: '좋은 정보네요.',
        likes: 1,
        created_at: '2025-07-31T09:05:00Z',
      },
      {
        id: '3',
        parent_id: '1',
        post_id: '1',
        user: { id: '101', nickname: '푸른고래' },
        content: '감사합니다!',
        likes: 0,
        created_at: '2025-07-31T09:06:00Z',
      },
    ],
    user: { id: '101', nickname: '푸른고래' },
    content: ` 안녕하세요! 저도 처음 임보 시작할 때 정말 떨렸어요.그래도 막상 아이를
        데려오면 생각보다 빨리 적응하더라고요.
        <br />
        제가 해보면서 느낀 점 몇 가지 공유드릴게요:
        <br />
        처음 집에 오면 너무 많은 자극을 주지 않는 게 좋아요. 조용히 편하게 쉴
        공간을 만들어주고, 한두 시간은 그냥 스스로 탐색하게 두세요.
        <br />
        기본 준비물은 사료, 물그릇, 배변패드, 담요, 안전문 정도면 충분했어요.
        <br />
        친해지려면 억지로 만지기보단 간식으로 손을 익숙하게 해주고, 같은
        공간에서 조용히 시간을 보내는 게 좋았어요.
        <br />
        처음이니까 너무 부담 가지지 않으셔도 돼요!아이도 분명 금방 마음을 열
        거예요. 응원합니다 💚`,
    likes: 3,
    created_at: '2025-07-31T09:00:00Z',
  },
  {
    id: '2',
    parent_id: '1',
    post_id: '1',
    user: { id: '121', nickname: 'ㄴㄴㅁ' },
    content: '좋은 정보네요.',
    likes: 1,
    created_at: '2025-07-31T09:05:00Z',
  },
  {
    id: '3',
    parent_id: '1',
    post_id: '1',
    user: { id: '101', nickname: '푸른고래' },
    content: '감사합니다!',
    likes: 0,
    created_at: '2025-07-31T09:06:00Z',
  },
  {
    id: '4',
    parent_id: null,
    reply_comments: [
      {
        id: '5',
        parent_id: '4',
        post_id: '1',
        user: { id: '102', nickname: 'ㅇㅎㄷ' },
        content: '답변 드릴게요.',
        likes: 5,
        created_at: '2025-07-31T09:11:00Z',
      },
      {
        id: '6',
        parent_id: '4',
        post_id: '1',
        user_id: '8',
        content: '저도 같은 생각입니다.',
        likes: 0,
        created_at: '2025-07-31T09:12:00Z',
      },
    ],
    post_id: '1',
    user: { id: '107', nickname: 'ㄴ' },
    content: '궁금한 점이 있어요.',
    likes: 2,
    created_at: '2025-07-31T09:10:00Z',
  },
  {
    id: '5',
    parent_id: '4',
    post_id: '1',
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '답변 드릴게요.',
    likes: 5,
    created_at: '2025-07-31T09:11:00Z',
  },
  {
    id: '6',
    parent_id: '4',
    post_id: '1',
    user_id: '8',
    content: '저도 같은 생각입니다.',
    likes: 0,
    created_at: '2025-07-31T09:12:00Z',
  },
  {
    id: '7',
    parent_id: null,
    reply_comments: [],
    post_id: '1',
    user_id: '2',
    content: '좋은 글이네요!',
    likes: 10,
    created_at: '2025-07-31T09:15:00Z',
  },
  {
    id: '8',
    parent_id: '7',
    post_id: '1',
    user_id: '3',
    content: '동의합니다.',
    likes: 1,
    created_at: '2025-07-31T09:16:00Z',
  },
  {
    id: '9',
    parent_id: '7',
    post_id: '1',
    user_id: '4',
    content: '정보 감사합니다.',
    likes: 0,
    created_at: '2025-07-31T09:17:00Z',
  },
  {
    id: '10',
    parent_id: null,
    reply_comments: [],
    post_id: '1',
    user_id: '9',
    content: '처음 보는 내용이에요.',
    likes: 0,
    created_at: '2025-07-31T09:20:00Z',
  },
  {
    id: '11',
    parent_id: '10',
    post_id: '1',
    user_id: '6',
    content: '저도 그랬어요!',
    likes: 2,
    created_at: '2025-07-31T09:21:00Z',
  },
  {
    id: '12',
    parent_id: '10',
    post_id: '1',
    user_id: '7',
    content: '재미있네요.',
    likes: 1,
    created_at: '2025-07-31T09:22:00Z',
  },

  // 게시물 2번
  {
    id: '13',
    parent_id: null,
    reply_comments: [],
    post_id: '2',
    user_id: '1',
    content: '이 게시물 유익하네요!',
    likes: 4,
    created_at: '2025-07-31T10:00:00Z',
  },
  {
    id: '14',
    parent_id: '13',
    post_id: '2',
    user_id: '2',
    content: '맞아요!',
    likes: 2,
    created_at: '2025-07-31T10:02:00Z',
  },
  {
    id: '15',
    parent_id: '13',
    post_id: '2',
    user_id: '3',
    content: '감사합니다.',
    likes: 1,
    created_at: '2025-07-31T10:03:00Z',
  },
  {
    id: '16',
    parent_id: null,
    post_id: '2',
    user_id: '5',
    content: '더 알고 싶어요.',
    likes: 0,
    created_at: '2025-07-31T10:05:00Z',
  },
];
