import {
  AnimalType,
  AnimalGender,
  FosterState,
  AnimalSize,
} from '@/types/animal/animal';
import {
  FosterListAnimalItem,
  FosterRecordAnimalItem,
} from '@/types/animal/animal-api';
import { CommentItem } from '@/types/comment/comment-api';
import { FosterRecordItem } from '@/types/foster-record/foster-record-api';
import { PostItem } from '@/types/post/post-api';

export const dummyPosts: PostItem[] = [
  {
    id: '1',
    user: { id: '101', nickname: '푸른고래' },
    images: ['https://source.unsplash.com/random/1'],
    title: 'My First Post',
    content: `안녕하세요, 이번에 처음으로 임시보호를 해보게 된 예비 임보자입니다. 아직 많이 부족하지만 용기를 내어 아이를 맞이하기로 결심했어요.<br/>
이번에 퍼디 매칭을 통해 한 달 정도 보호할 강아지를 데려올 예정인데요, 막상 준비를 하려니 어떤 것부터 챙겨야 할지 막막해서 이렇게 글을 남깁니다.<br/>
혹시 임보 경험이 있으신 분들께 몇 가지 여쭤보고 싶어요.<br/>
집에 처음 들어올 때 강아지가 덜 불안해할 수 있도록 어떤 환경을 만들어주면 좋을까요?<br/>
꼭 사야 하는 기본 용품이나 준비물이 있을까요?<br/>
처음 며칠 동안 특히 조심해야 할 점이 있다면 알려주세요.<br/>
혹시 아이와 조금이라도 빨리 친해질 수 있는 팁이 있을까요?<br/>
주변에서 다들 “처음엔 낯설어할 거야”라고 말씀하시는데, 제가 더 긴장하고 있나 봅니다.<br/>
잘 해주고 싶은 마음이 커서 걱정도 많네요.<br/>
선배 임보자님들의 경험이나 작은 팁이라도 정말 큰 도움이 될 것 같아요. 읽어주셔서 감사합니다. 많은 조언 부탁드립니다! 🥹`,
    likes: 5,
    views: 34,
    created_at: '2025-07-21T10:15:00Z',
  },
  {
    id: '2',
    user: { id: '102', nickname: '푸른래' },
    images: [],
    title: 'Summer Vibes',
    content: 'Loving the summer weather lately ☀️',
    likes: 12,
    views: 78,
    created_at: '2025-07-22T14:30:00Z',
  },
  {
    id: '3',
    user: { id: '103', nickname: 'ss래' },
    images: ['https://source.unsplash.com/random/3'],
    title: 'My Dog Max',
    content: "Here's a picture of my dog Max at the park.",
    likes: 20,
    views: 112,
    created_at: '2025-07-23T09:05:00Z',
  },
  {
    id: '4',
    user: { id: '104', nickname: 'dd' },
    images: ['https://source.unsplash.com/random/4'],
    title: 'New Coffee Place',
    content: 'Just discovered this amazing café downtown!',
    likes: 9,
    views: 54,
    created_at: '2025-07-24T18:40:00Z',
  },
  {
    id: '5',
    user: { id: '105', nickname: 'dㅇ' },
    images: [],
    title: 'Looking for Book Recommendations',
    content: 'What’s a good novel to read these days?',
    likes: 2,
    views: 26,
    created_at: '2025-07-25T08:22:00Z',
  },
  {
    id: '6',
    user: { id: '106', nickname: '푸른고ㄶ래' },
    images: ['https://source.unsplash.com/random/6'],
    title: 'My Artwork 🎨',
    content: 'Sharing one of my recent paintings.',
    likes: 17,
    views: 94,
    created_at: '2025-07-26T13:55:00Z',
  },
  {
    id: '7',
    user: { id: '101', nickname: '푸른고래' },
    images: ['https://source.unsplash.com/random/7'],
    title: 'Weekend Hike',
    content: 'Went hiking in the mountains. Nature is healing.',
    likes: 15,
    views: 88,
    created_at: '2025-07-27T16:00:00Z',
  },
  {
    id: '8',
    user: { id: '101', nickname: '푸른고래' },
    images: [],
    title: 'Question About React',
    content: 'How do I handle state across multiple components?',
    likes: 3,
    views: 42,
    created_at: '2025-07-28T11:12:00Z',
  },
  {
    id: '9',
    user: { id: '101', nickname: '푸른고래' },
    images: ['https://source.unsplash.com/random/9'],
    title: 'City Lights',
    content: 'Captured this shot last night. Love the city glow.',
    likes: 22,
    views: 130,
    created_at: '2025-07-29T21:47:00Z',
  },
  {
    id: '10',
    user: { id: '111', nickname: 'ㅇㅇ' },
    images: ['https://source.unsplash.com/random/10'],
    title: 'Trying Out Tailwind CSS',
    content: 'Built a page with Tailwind today. Super clean and fast.',
    likes: 6,
    views: 48,
    created_at: '2025-07-30T07:30:00Z',
  },
  {
    id: '11',
    user: { id: '141', nickname: 'ㅇㄴㅁㄴ' },
    images: ['https://source.unsplash.com/random/9'],
    title: 'City Lights',
    content: 'Captured this shot last night. Love the city glow.',
    likes: 22,
    views: 130,
    created_at: '2025-07-29T21:47:00Z',
  },
  {
    id: '12',
    user: { id: '107', nickname: 'ㅓㅓ' },
    images: ['https://source.unsplash.com/random/10'],
    title: 'Trying Out Tailwind CSS',
    content: 'Built a page with Tailwind today. Super clean and fast.',
    likes: 6,
    views: 48,
    created_at: '2025-07-30T07:30:00Z',
  },
];

export const dummyComments: CommentItem[] = [
  // 게시물 1번
  {
    id: '1',
    parent_id: null,
    post_id: '1',
    reply_comments: [
      {
        id: '2',
        parent_id: '1',
        post_id: '1',
        user: { id: '121', nickname: 'ㄴㄴㅁ' },
        content: '좋은 정보네요.',
        likes: 1,
        created_at: '2025-07-31T09:05:00Z',
      },
      {
        id: '3',
        parent_id: '1',
        post_id: '1',
        user: { id: '101', nickname: '푸른고래' },
        content: '감사합니다!',
        likes: 0,
        created_at: '2025-07-31T09:06:00Z',
      },
    ],
    user: { id: '101', nickname: '푸른고래' },
    content: ` 안녕하세요! 저도 처음 임보 시작할 때 정말 떨렸어요.그래도 막상 아이를
        데려오면 생각보다 빨리 적응하더라고요.
        <br />
        제가 해보면서 느낀 점 몇 가지 공유드릴게요:
        <br />
        처음 집에 오면 너무 많은 자극을 주지 않는 게 좋아요. 조용히 편하게 쉴
        공간을 만들어주고, 한두 시간은 그냥 스스로 탐색하게 두세요.
        <br />
        기본 준비물은 사료, 물그릇, 배변패드, 담요, 안전문 정도면 충분했어요.
        <br />
        친해지려면 억지로 만지기보단 간식으로 손을 익숙하게 해주고, 같은
        공간에서 조용히 시간을 보내는 게 좋았어요.
        <br />
        처음이니까 너무 부담 가지지 않으셔도 돼요!아이도 분명 금방 마음을 열
        거예요. 응원합니다 💚`,
    likes: 3,
    created_at: '2025-07-31T09:00:00Z',
  },
  {
    id: '2',
    parent_id: '1',
    post_id: '1',
    reply_comments: null,
    user: { id: '121', nickname: 'ㄴㄴㅁ' },
    content: '좋은 정보네요.',
    likes: 1,
    created_at: '2025-07-31T09:05:00Z',
  },
  {
    id: '3',
    parent_id: '1',
    post_id: '1',
    reply_comments: null,
    user: { id: '101', nickname: '푸른고래' },
    content: '감사합니다!',
    likes: 0,
    created_at: '2025-07-31T09:06:00Z',
  },
  {
    id: '4',
    parent_id: null,
    reply_comments: [
      {
        id: '5',
        parent_id: '4',
        post_id: '1',
        user: { id: '102', nickname: 'ㅇㅎㄷ' },
        content: '답변 드릴게요.',
        likes: 5,
        created_at: '2025-07-31T09:11:00Z',
      },
      {
        id: '6',
        parent_id: '4',
        post_id: '1',
        user: { id: '102', nickname: 'ㅇㅎㄷ' },
        content: '저도 같은 생각입니다.',
        likes: 0,
        created_at: '2025-07-31T09:12:00Z',
      },
    ],
    post_id: '1',
    user: { id: '107', nickname: 'ㄴ' },
    content: '궁금한 점이 있어요.',
    likes: 2,
    created_at: '2025-07-31T09:10:00Z',
  },
  {
    id: '5',
    parent_id: '4',
    post_id: '1',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '답변 드릴게요.',
    likes: 5,
    created_at: '2025-07-31T09:11:00Z',
  },
  {
    id: '6',
    parent_id: '4',
    post_id: '1',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '저도 같은 생각입니다.',
    likes: 0,
    created_at: '2025-07-31T09:12:00Z',
  },
  {
    id: '7',
    parent_id: null,
    reply_comments: [],
    post_id: '1',
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '좋은 글이네요!',
    likes: 10,
    created_at: '2025-07-31T09:15:00Z',
  },
  {
    id: '8',
    parent_id: '7',
    post_id: '1',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '동의합니다.',
    likes: 1,
    created_at: '2025-07-31T09:16:00Z',
  },
  {
    id: '9',
    parent_id: '7',
    post_id: '1',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '정보 감사합니다.',
    likes: 0,
    created_at: '2025-07-31T09:17:00Z',
  },
  {
    id: '10',
    parent_id: null,
    reply_comments: [],
    post_id: '1',
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '처음 보는 내용이에요.',
    likes: 0,
    created_at: '2025-07-31T09:20:00Z',
  },
  {
    id: '11',
    parent_id: '10',
    post_id: '1',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '저도 그랬어요!',
    likes: 2,
    created_at: '2025-07-31T09:21:00Z',
  },
  {
    id: '12',
    parent_id: '10',
    post_id: '1',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '재미있네요.',
    likes: 1,
    created_at: '2025-07-31T09:22:00Z',
  },

  // 게시물 2번
  {
    id: '13',
    parent_id: null,
    reply_comments: [],
    post_id: '2',
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '이 게시물 유익하네요!',
    likes: 4,
    created_at: '2025-07-31T10:00:00Z',
  },
  {
    id: '14',
    parent_id: '13',
    post_id: '2',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '맞아요!',
    likes: 2,
    created_at: '2025-07-31T10:02:00Z',
  },
  {
    id: '15',
    parent_id: '13',
    post_id: '2',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '감사합니다.',
    likes: 1,
    created_at: '2025-07-31T10:03:00Z',
  },
  {
    id: '16',
    parent_id: null,
    post_id: '2',
    reply_comments: null,
    user: { id: '102', nickname: 'ㅇㅎㄷ' },
    content: '더 알고 싶어요.',
    likes: 0,
    created_at: '2025-07-31T10:05:00Z',
  },
];

export const dummyAnimals: FosterRecordAnimalItem[] = [
  {
    id: 1,
    name: 'Buddy',
    type: AnimalType.DOG,
    images: ['/images/animal01.jpg'],
    breed: 'Golden Retriever',
    age: 3,
    gender: AnimalGender.MALE,
    foster_duration: 12,
    state: FosterState.IN_PROGRESS,
    foster_match_id: '1',
  },
  {
    id: 2,
    name: 'Mochi',
    type: AnimalType.CAT,
    images: ['/images/animal01.jpg'],
    breed: 'Persian',
    age: 2,
    gender: AnimalGender.FEMALE,
    foster_duration: 25,
    state: FosterState.FOSTERED,
    foster_match_id: '2',
  },
  {
    id: 3,
    name: 'Charlie',
    type: AnimalType.DOG,
    images: ['/images/animal01.jpg'],
    breed: 'Shih Tzu',
    age: 5,
    gender: AnimalGender.MALE,
    foster_duration: 40,
    state: FosterState.FOSTERED,
    foster_match_id: '3',
  },
  {
    id: 4,
    name: 'Nabi',
    type: AnimalType.CAT,
    images: ['/images/animal01.jpg'],
    breed: 'Korean Shorthair',
    age: 1,
    gender: AnimalGender.FEMALE,
    foster_duration: 7,
    state: FosterState.IN_PROGRESS,
    foster_match_id: '4',
  },
  {
    id: 5,
    name: 'Max',
    type: AnimalType.DOG,
    images: ['/images/animal01.jpg'],
    breed: 'Jindo',
    age: 4,
    gender: AnimalGender.MALE,
    foster_duration: 18,
    state: FosterState.IN_PROGRESS,
    foster_match_id: '5',
  },
  {
    id: 6,
    name: 'Luna',
    type: AnimalType.CAT,
    images: ['/images/animal01.jpg'],
    breed: 'Russian Blue',
    age: 3,
    gender: AnimalGender.FEMALE,
    foster_duration: 60,
    state: FosterState.FOSTERED,
    foster_match_id: '6',
  },
  {
    id: 7,
    name: 'Bori',
    type: AnimalType.DOG,
    images: ['/images/animal01.jpg'],
    breed: 'Poodle',
    age: 2,
    gender: AnimalGender.FEMALE,
    foster_duration: 10,
    state: FosterState.IN_PROGRESS,
    foster_match_id: '7',
  },
  {
    id: 8,
    name: 'Tiger',
    type: AnimalType.CAT,
    images: ['/images/animal01.jpg'],
    breed: 'Bengal',
    age: 6,
    gender: AnimalGender.MALE,
    foster_duration: 90,
    state: FosterState.FOSTERED,
    foster_match_id: '8',
  },
  {
    id: 9,
    name: 'Toto',
    type: AnimalType.DOG,
    images: ['/images/animal01.jpg'],
    breed: 'Corgi',
    age: 3,
    gender: AnimalGender.MALE,
    foster_duration: 14,
    state: FosterState.FOSTERED,
    foster_match_id: '9',
  },
  {
    id: 10,
    name: 'Yuna',
    type: AnimalType.CAT,
    images: ['/images/animal01.jpg'],
    breed: 'Siamese',
    age: 4,
    gender: AnimalGender.FEMALE,
    foster_duration: 5,
    state: FosterState.IN_PROGRESS,
    foster_match_id: '10',
  },
];

export const fosterRecordDummyData: FosterRecordItem[] = [
  {
    id: '1',
    state: FosterState.IN_PROGRESS,
    organization: {
      id: 'o1',
      name: '퍼디 동물보호소',
      phone_number: '02-1234-5678',
      zipcode: '04524',
      address: '서울특별시 강남구 테헤란로 123',
      address_detail: '3층 302호',
      email: 'info@furdie.org',
    },
    animal: {
      name: '초코',
      type: AnimalType.DOG,
      breed: '푸들',
      age: 3,
      remark:
        '꼬리 만지는 걸 싫어함. 나이가 좀 있어 각별한 관리가 필요함. 심장병으로인해 매일 약을 챙겨먹어야 함.',
      gender: AnimalGender.FEMALE,
      images: ['/images/animal01.jpg'],
    },
    created_at: new Date('2025-07-01T10:00:00Z'),
    foster_records: [
      {
        id: '0_q',
        images: ['/images/animal01.jpg'],
        content: '첫날부터 활발하게 잘 놀았어요!',
        health_note: '식욕 좋고 대소변 문제 없음.',
        created_at: '2025-08-02T10:00:00Z',
        updated_at: new Date(),
      },
      {
        id: '0',
        images: ['/images/animal01.jpg'],
        content: '첫날부터 활발하게 잘 놀았어요!',
        health_note: '식욕 좋고 대소변 문제 없음.',
        created_at: '2025-08-01T10:00:00Z',
        updated_at: new Date(),
      },
      {
        id: '1',
        images: [
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
        ],
        content: '첫날부터 활발하게 잘 놀았어요!',
        health_note: '식욕 좋고 대소변 문제 없음.',
        created_at: '2025-07-01T10:00:00Z',
        updated_at: new Date(),
      },
      {
        id: '2',
        images: [
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
        ],
        content: '산책 중 낯선 강아지를 보고 짖음.',
        health_note: '약간의 분리불안 있음.',
        created_at: '2025-07-03T14:20:00Z',
        updated_at: new Date(),
      },
      {
        id: '3',
        images: [
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
        ],
        content: '고양이라 그런지 하루 종일 자네요.',
        health_note: '건강 양호, 식사 규칙적.',
        created_at: '2025-07-05T08:30:00Z',
        updated_at: new Date(),
      },
      {
        id: '4',
        images: ['/images/animal01.jpg', '/images/animal01.jpg'],
        content: '소리에 민감하지만 금방 적응함.',
        health_note: '이상 없음.',
        created_at: '2025-07-07T19:10:00Z',
        updated_at: new Date(),
      },
      {
        id: '5',
        images: [
          '/images/animal01.jpg',
          '/images/animal01.jpg',
          '/images/animal01.jpg',
        ],
        content: '매일 똑같은 담요 위에만 앉아요.',
        health_note: '소화기능 양호.',
        created_at: '2025-07-09T11:00:00Z',
        updated_at: new Date(),
      },
      {
        id: '6',
        images: ['/images/animal01.jpg'],
        content: '산책 중 풀밭에서 뒹굴기를 좋아함.',
        health_note: '피부 가려움 주의.',
        created_at: '2025-07-10T13:40:00Z',
        updated_at: new Date(),
      },
      {
        id: '7',
        images: ['/images/animal01.jpg'],
        content: '캣타워 좋아함, 활동량 많음.',
        health_note: '귀 청소 필요.',
        created_at: '2025-07-12T09:25:00Z',
        updated_at: new Date(),
      },
      {
        id: '8',
        images: ['/images/animal01.jpg'],
        content: '조금 무서움이 많지만 사람을 따름.',
        health_note: '예방접종 완료.',
        created_at: '2025-07-13T18:00:00Z',
        updated_at: new Date(),
      },
      {
        id: '9',
        images: ['/images/animal01.jpg'],
        content: '첫날 밤에 낑낑거렸지만 이튿날 잠잠.',
        health_note: '배변훈련 중.',
        created_at: '2025-07-15T07:45:00Z',
        updated_at: new Date(),
      },
      {
        id: '10',
        images: ['/images/animal01.jpg'],
        content: '처음 와서 2일 동안 식욕이 없었지만 지금은 잘 먹음.',
        health_note: '스트레스 적응 완료.',
        created_at: '2025-07-17T16:10:00Z',
        updated_at: new Date(),
      },
    ],
  },
];

export const dummyFosterAnimals: FosterListAnimalItem[] = [
  {
    id: '1',
    name: 'Buddy',
    type: AnimalType.DOG,
    image: '/images/animal01.jpg',
    breed: 'Golden Retriever',
    size: AnimalSize.SMALL,
    age: 3,
    gender: AnimalGender.MALE,
    foster_duration: 12,
    isBookmarked: true,
    animal_healths: ['접종완료', '양호', '중성화 완료'],
    animal_personalitys: [
      '입질 없음',
      '조용함',
      '사람 친화적 아이',
      '다른 동물과 잘 어울림',
    ],
    foster_environments: [
      '조용한 집',
      '산책/놀이 등 활동 가능',
      '사람과 잦은 교류 가능',
      '배변 훈련 시도 가능',
    ],
    isEmergency: true,
    organization: {
      id: '1',
      name: '보듬컴퍼니',
      address: '중랑구 상봉동',
      address_detail: '2-4-37',
      phone_number: '010-2222-1022',
    },
  },
  {
    id: '2',
    name: 'Mochi',
    type: AnimalType.CAT,
    size: AnimalSize.SMALL,
    image: '/images/animal01.jpg',
    breed: 'Persian',
    age: 2,
    gender: AnimalGender.FEMALE,
    foster_duration: 25,
    isBookmarked: true,
    animal_healths: ['중성화 완료', '피부 치료 필요'],
    animal_personalitys: ['사람 좋아함', '애교 많음', '분리불안 있음'],
    foster_environments: ['항상 집에 사람이 있는 환경', '교감이 잦은 환경'],
    isEmergency: true,
    organization: {
      id: '3',
      name: '푸른보호소',
      address: '마포구 망원동',
      address_detail: '58-12',
      phone_number: '010-7777-8888',
    },
  },
  {
    id: '3',
    name: 'Charlie',
    size: AnimalSize.MEDIUM,
    type: AnimalType.DOG,
    image: '/images/animal01.jpg',
    breed: 'Shih Tzu',
    age: 5,
    gender: AnimalGender.MALE,
    foster_duration: 40,
    isBookmarked: false,
    animal_healths: ['접종 필요', '양호'],
    animal_personalitys: ['조용함', '낯가림 있음', '혼자 있기 좋아함'],
    foster_environments: ['조용한 가정', '사람이 적은 환경'],
    isEmergency: false,
    organization: {
      id: '4',
      name: '달빛 보호센터',
      address: '서초구 방배동',
      address_detail: '24-11',
      phone_number: '010-9999-1010',
    },
  },
  {
    id: '4',
    name: 'Nabi',
    type: AnimalType.CAT,
    size: AnimalSize.SMALL,
    image: '/images/animal01.jpg',
    breed: 'Korean Shorthair',
    age: 1,
    gender: AnimalGender.FEMALE,
    foster_duration: 7,
    isBookmarked: true,
    animal_healths: ['접종완료', '양호'],
    animal_personalitys: ['밝음', '다른 동물 좋아함'],
    foster_environments: ['다른 반려동물과 함께 지내는 가정', '활동적인 환경'],
    isEmergency: false,
    organization: {
      id: '5',
      name: '콩콩 쉼터',
      address: '은평구 구산동',
      address_detail: '9-22',
      phone_number: '010-5555-6666',
    },
  },
  {
    id: '5',
    name: 'Max',
    type: AnimalType.DOG,
    size: AnimalSize.MEDIUM,
    image: '/images/animal01.jpg',
    breed: 'Jindo',
    age: 4,
    gender: AnimalGender.MALE,
    foster_duration: 18,
    isBookmarked: false,
    animal_healths: ['중성화 완료', '약 복용 필요'],
    animal_personalitys: ['순함', '사람 좋아함', '조용함'],
    foster_environments: ['약 복용 관리 가능한 가정', '규칙적인 생활 가능'],
    isEmergency: false,
    organization: {
      id: '6',
      name: '보호의집',
      address: '종로구 혜화동',
      address_detail: '31-18',
      phone_number: '010-1212-3434',
    },
  },
  {
    id: '6',
    name: 'Luna',
    type: AnimalType.CAT,
    size: AnimalSize.LARGE,
    image: '/images/animal01.jpg',
    breed: 'Russian Blue',
    age: 3,
    gender: AnimalGender.FEMALE,
    foster_duration: 60,
    isBookmarked: true,
    animal_healths: ['접종완료', '양호'],
    animal_personalitys: ['활발함', '호기심 많음', '사람 친화적'],
    foster_environments: ['활동적인 가정', '아이들과 잘 어울리는 환경'],
    isEmergency: false,
    organization: {
      id: '7',
      name: '사랑의쉼터',
      address: '송파구 잠실동',
      address_detail: '88-14',
      phone_number: '010-8989-5656',
    },
  },
  {
    id: '7',
    name: 'Bori',
    type: AnimalType.DOG,
    size: AnimalSize.LARGE,
    image: '/images/animal01.jpg',
    breed: 'Poodle',
    age: 2,
    gender: AnimalGender.FEMALE,
    foster_duration: 10,
    isBookmarked: false,
    animal_healths: ['접종 필요', '피부 관리 필요'],
    animal_personalitys: ['낯가림 있음', '사람에게 서서히 친해짐'],
    foster_environments: ['조용한 가정', '인내심 있는 보호자'],
    isEmergency: false,
    organization: {
      id: '8',
      name: '루나 센터',
      address: '용산구 이촌동',
      address_detail: '6-5-17',
      phone_number: '010-5656-7878',
    },
  },
  {
    id: '8',
    name: 'Tiger',
    type: AnimalType.CAT,
    size: AnimalSize.SMALL,
    image: '/images/animal01.jpg',
    breed: 'Bengal',
    age: 6,
    gender: AnimalGender.MALE,
    foster_duration: 90,
    isBookmarked: true,
    animal_healths: ['접종완료', '양호'],
    animal_personalitys: ['활발함', '호기심 많음', '사람 친화적'],
    foster_environments: ['활동적인 가정', '아이들과 잘 어울리는 환경'],
    isEmergency: true,
    organization: {
      id: '7',
      name: '사랑의쉼터',
      address: '송파구 잠실동',
      address_detail: '88-14',
      phone_number: '010-8989-5656',
    },
  },
  {
    id: '9',
    name: 'Toto',
    type: AnimalType.DOG,
    size: AnimalSize.SMALL,
    image: '/images/animal01.jpg',
    breed: 'Corgi',
    age: 3,
    gender: AnimalGender.MALE,
    foster_duration: 14,
    isBookmarked: false,
    animal_healths: ['중성화 완료', '약 복용 필요'],
    animal_personalitys: ['순함', '사람 좋아함', '조용함'],
    foster_environments: ['약 복용 관리 가능한 가정', '규칙적인 생활 가능'],
    isEmergency: false,
    organization: {
      id: '6',
      name: '보호의집',
      address: '종로구 혜화동',
      address_detail: '31-18',
      phone_number: '010-1212-3434',
    },
  },
  {
    id: '10',
    name: 'Yuna',
    type: AnimalType.CAT,
    size: AnimalSize.SMALL,
    image: '/images/animal01.jpg',
    breed: 'Siamese',
    age: 4,
    gender: AnimalGender.FEMALE,
    foster_duration: 5,
    isBookmarked: true,
    animal_healths: ['접종완료', '양호'],
    animal_personalitys: ['밝음', '다른 동물 좋아함'],
    foster_environments: ['다른 반려동물과 함께 지내는 가정', '활동적인 환경'],
    isEmergency: true,
    organization: {
      id: '5',
      name: '콩콩 쉼터',
      address: '은평구 구산동',
      address_detail: '9-22',
      phone_number: '010-5555-6666',
    },
  },
];
