import {
  AnimalGender,
  AnimalStatus,
  AnimalType,
} from '@/entities/animal/animal';
import { FosterRecordAnimalItem } from '@/entities/animal/animal-api';

export const dummyFosterAnimals: FosterRecordAnimalItem[] = [
  {
    id: 'a1',
    name: '코코',
    type: AnimalType.DOG,
    gender: AnimalGender.FEMALE,
    breed: '푸들',
    birth_date: new Date('2020-05-12'),
    images: ['/images/animal01.jpg'],
    foster_duration: 21,
    state: AnimalStatus.IN_PROGRESS,
  },
  {
    id: 'a2',
    name: '보리',
    type: AnimalType.CAT,
    gender: AnimalGender.MALE,
    breed: '러시안블루',
    birth_date: new Date('2021-11-02'),
    images: ['/images/animal02.jpg'],
    foster_duration: 75,
    state: AnimalStatus.IN_PROGRESS,
  },
  {
    id: 'a3',
    name: '몽이',
    type: AnimalType.DOG,
    gender: AnimalGender.MALE,
    breed: '말티즈',
    birth_date: new Date('2019-09-15'),
    images: ['/images/animal03.jpg'],
    foster_duration: 56,
    state: AnimalStatus.IN_PROGRESS,
  },
  {
    id: 'a4',
    name: '하루',
    type: AnimalType.CAT,
    gender: AnimalGender.FEMALE,
    breed: '페르시안',
    birth_date: new Date('2022-03-08'),
    images: ['/images/animal01.jpg'],
    foster_duration: 256,
    state: AnimalStatus.COMPLETED,
  },
  {
    id: 'a5',
    name: '초코',
    type: AnimalType.DOG,
    gender: AnimalGender.MALE,
    breed: '시츄',
    birth_date: new Date('2018-12-30'),
    images: ['/images/animal02.jpg'],
    foster_duration: 27,
    state: AnimalStatus.COMPLETED,
  },
  {
    id: 'a6',
    name: '냥이',
    type: AnimalType.CAT,
    gender: AnimalGender.FEMALE,
    breed: '코리안숏헤어',
    birth_date: new Date('2020-01-20'),
    images: ['/images/animal03.jpg'],
    foster_duration: 6,
    state: AnimalStatus.IN_PROGRESS,
  },
  {
    id: 'a7',
    name: '두리',
    type: AnimalType.DOG,
    gender: AnimalGender.FEMALE,
    breed: '골든리트리버',
    birth_date: new Date('2017-07-11'),
    images: ['/images/animal01.jpg'],
    foster_duration: 12,
    state: AnimalStatus.COMPLETED,
  },
  {
    id: 'a8',
    name: '루이',
    type: AnimalType.DOG,
    gender: AnimalGender.MALE,
    breed: '비숑 프리제',
    birth_date: new Date('2021-04-04'),
    images: ['/images/animal02.jpg'],
    foster_duration: 211,
    state: AnimalStatus.IN_PROGRESS,
  },
  {
    id: 'a9',
    name: '하늘',
    type: AnimalType.CAT,
    gender: AnimalGender.FEMALE,
    breed: '샴',
    birth_date: new Date('2019-06-25'),
    images: ['/images/animal03.jpg'],
    foster_duration: 2121,
    state: AnimalStatus.IN_PROGRESS,
  },
  {
    id: 'a10',
    name: '감자',
    type: AnimalType.DOG,
    gender: AnimalGender.MALE,
    breed: '믹스',
    birth_date: new Date('2023-02-10'),
    images: ['/images/animal01.jpg'],
    foster_duration: 100,
    state: AnimalStatus.IN_PROGRESS,
  },
];
