import { AnimalType, AnimalGender, AnimalSize } from '@/types/animal/animal';

export enum AnimalAge {
  JUVENILE = 'JUVENILE', //2살 미만
  ADULT = 'ADULT', //8살 미말
  SENIOR = 'SENIOR', //8살 이상
}

export enum AnimalPersonality {
  QUIET = 'QUIET',
  ENERGETIC = 'ENERGETIC',
  INDEPENDENCE = 'INDEPENDENCE',
  SENSITIVITY = 'SENSITIVITY',
  FRIENDLY_WITH_PEOPLE = 'FRIENDLY_WITH_PEOPLE',
  GOOD_WITH_OTHER_ANIMAL = 'GOOD_WITH_OTHER_ANIMAL',
  POTTY_TRAINING_COMPLETION = 'POTTY_TRAINING_COMPLETION',
  NO_BITING = 'NO_BITING',
}

export enum AnimalEnvironment {
  QUIET_ENVIRONMENT = 'QUIET_ENVIRONMENT',
  AVAILABILITY_FOR_WALKS_PLAY = 'AVAILABILITY_FOR_WALKS_PLAY',
  FREQUENT_INTERACTION_WITH_PETS = 'FREQUENT_INTERACTION_WITH_PETS',
  PRESENCE_OF_OTHER_ANIMAL = 'PRESENCE_OF_OTHER_ANIMAL',
  WILLINGNESS_FOR_POTTY_TRAINING = 'WILLINGNESS_FOR_POTTY_TRAINING',
  PATIENCE_WITH_BARKING_BITING = 'PATIENCE_WITH_BARKING_BITING',
  CARE_FOR_SENSITIVE_OR_FEARFUL_PETS = 'CARE_FOR_SENSITIVE_OR_FEARFUL_PETS',
  HOUSEHOLD_WITH_YOUNG_CHILDREN = 'HOUSEHOLD_WITH_YOUNG_CHILDREN',
}

export enum AnimalHealth {
  NEUTERED = 'NEUTERED',
  VACCINATED = 'VACCINATED',
  MICROCHIPPED = 'MICROCHIPPED',
  HEARTWORM_TESTED = 'HEARTWORM_TESTED',
  DEWORMED = 'DEWORMED',
  FLEA_TICK_TREATED = 'FLEA_TICK_TREATED',
}

export enum AnimalPeriod {
  SHORT_TERM_FOSTER = 'SHORT_TERM_FOSTER', //1개월 미만
  MID_TERM_FOSTER = 'MID_TERM_FOSTER', // 3개월 미만
  LONG_TERM_FOSTER = 'LONG_TERM_FOSTER', // 3개월 이상
}

export enum AnimalSpecialNote {
  SEPARATION_ANXIETY = 'SEPARATION_ANXIETY',
  MEDICATION_REQUIRED = 'MEDICATION_REQUIRED',
  POTTY_ACCIDENTS = 'POTTY_ACCIDENTS',
  AGGRESSION_TOWARD_OTHER_ANIMALS = 'AGGRESSION_TOWARD_OTHER_ANIMALS',
  ONGOING_TREATMENT_OR_RECOVERY = 'ONGOING_TREATMENT_OR_RECOVERY',
  DISABLED_OR_ILL_PETS_ACCEPTED = 'DISABLED_OR_ILL_PETS_ACCEPTED',
}

export type AnimalCondition = {
  id: string;
  type: AnimalType;
  size: AnimalSize;
  gender: AnimalGender;
  animal_age: AnimalAge;
  animal_healths: AnimalHealth[];
  animal_personalitys: AnimalPersonality[];
  foster_environments: AnimalEnvironment[];
  special_notes_animals: AnimalSpecialNote[];
  foster_period: AnimalPeriod;
  created_at: Date;
  updated_at: Date;
  animal_id: string;
};
