export enum AnimalType {
  DOG = 'DOG',
  CAT = 'CAT',
}

export enum AnimalGender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
}

export enum AnimalSize {
  SMALL = 'SMALL',
  MEDIUM = 'MEDIUM',
  LARGE = 'LARGE',
}

export enum FosterState {
  IN_PROGRESS = 'IN_PROGRESS',
  FOSTERED = 'FOSTERED',
  ADOPTED = 'ADOPTED ',
}

export enum ANIMAL_AGE {
  JUVENILE = 'JUVENILE',
  ADULT = 'ADULT',
  SENIOR = 'SENIOR',
}

export enum ANIMAL_PERSONALITYS {
  QUIET = 'QUIET',
  ENERGETIC = 'ENERGETIC',
  INDEPENDENCE = 'INDEPENDENCE',
  SENSITIVITY = 'SENSITIVITY',
  FRIENDLY_WITH_PEOPLE = 'FRIENDLY_WITH_PEOPLE',
  GOOD_WITH_OTHER_ANIMAL = 'GOOD_WITH_OTHER_ANIMAL',
  POTTY_TRAINING_COMPLETION = 'POTTY_TRAINING_COMPLETION',
  NO_BITING = 'NO_BITING',
}

export enum ANIMAL_ENVIRONMENT {
  QUIET_ENVIRONMENT = 'QUIET_ENVIRONMENT',
  AVAILABILITY_FOR_WALKS_PLAY = 'AVAILABILITY_FOR_WALKS_PLAY',
  FREQUENT_INTERACTION_WITH_PETS = 'FREQUENT_INTERACTION_WITH_PETS',
  PRESENCE_OF_OTHER_ANIMAL = 'PRESENCE_OF_OTHER_ANIMAL',
  WILLINGNESS_FOR_POTTY_TRAINING = 'WILLINGNESS_FOR_POTTY_TRAINING',
  PATIENCE_WITH_BARKING_BITING = 'PATIENCE_WITH_BARKING_BITING',
  CARE_FOR_SENSITIVE_OR_FEARFUL_PETS = 'CARE_FOR_SENSITIVE_OR_FEARFUL_PETS',
  HOUSEHOLD_WITH_YOUNG_CHILDREN = 'HOUSEHOLD_WITH_YOUNG_CHILDREN',
}

export enum ANIMAL_HEALTH {
  NEUTERED = 'NEUTERED',
  VACCINATED = 'VACCINATED',
  MICROCHIPPED = 'MICROCHIPPED',
  HEARTWORM_TESTED = 'HEARTWORM_TESTED',
  DEWORMED = 'DEWORMED',
  FLEA_TICK_TREATED = 'FLEA_TICK_TREATED',
}

export enum ANIMAL_PERIOD {
  SHORT_TERM_FOSTER = 'SHORT_TERM_FOSTER',
  MID_TERM_FOSTER = 'MID_TERM_FOSTER',
  LONG_TERM_FOSTER = 'LONG_TERM_FOSTER',
}

export enum ANIMAL_SPECIAL_NOTES {
  SEPARATION_ANXIETY = 'SEPARATION_ANXIETY',
  MEDICATION_REQUIRED = 'MEDICATION_REQUIRED',
  POTTY_ACCIDENTS = 'POTTY_ACCIDENTS',
  AGGRESSION_TOWARD_OTHER_ANIMALS = 'AGGRESSION_TOWARD_OTHER_ANIMALS',
  ONGOING_TREATMENT_OR_RECOVERY = 'ONGOING_TREATMENT_OR_RECOVERY',
  DISABLED_OR_ILL_PETS_ACCEPTED = 'DISABLED_OR_ILL_PETS_ACCEPTED',
}

export type AnimalCondition = {
  id: string;
  name: string;
  type: AnimalType;
  size: AnimalSize;
  gender: AnimalGender;
  animal_age: ANIMAL_AGE;
  animal_healths: ANIMAL_HEALTH[];
  animal_personalitys: ANIMAL_PERSONALITYS[];
  foster_environments: ANIMAL_ENVIRONMENT[];
  special_notes_animalss: ANIMAL_SPECIAL_NOTES[];
  foster_period: ANIMAL_PERIOD;
  created_at: Date;
  updated_at: Date;
  animal_id: string;
};
