export const dogBreeds: string[] = [
  '아키타(Akita)',
  '아메리칸 코커 스패니얼(American Cocker Spaniel)',
  '아메리칸 에스키모 도그(American Eskimo Dog)',
  '아메리칸 폭스하운드(American Foxhound)',
  '아메리칸 워터 스패니얼(American Water Spaniel)',
  '아자와크(Afghan Hound Azawakh)',
  '아프간 하운드(Afghan Hound)',
  '알래스칸 맬러뮤트(Alaskan Malamute)',
  '안달루시안 하운드(Andalusian Hound)',
  '에어데일 테리어(Airedale Terrier)',
  '에우로하운드(Eurohound)',
  '아이리시 세터(Irish Setter)',
  '아이리시 테리어(Irish Terrier)',
  '아이리시 울프하운드(Irish Wolfhound)',
  '이비잔 하운드(Ibizan Hound)',
  '아펜핀셔(Affenpinscher)',
  '올드 잉글리시 시프도그(Old English Sheepdog)',
  '오스트레일리안 케르피(Australian Kelpie)',
  '오스트레일리안 캐틀도그(Australian Cattle Dog)',
  '오가르 폴스키(Ogar Polski)',
  '오터하운드(Otterhound)',
  '잉글리시 포인터(English Pointer)',
  '이탈리안 그레이하운드(Italian Greyhound)',
  '잉글리시 코커 스패니얼(English Cocker Spaniel)',
  '잉글리시 세터(English Setter)',
  '잉글리시 스프링어 스패니얼(English Springer Spaniel)',
  '잉글리시 토이 스패니얼(English Toy Spaniel)',
  '잭 러셀 테리어(Jack Russell Terrier)',
  '자이언트 슈나우저(Giant Schnauzer)',
  '저먼 셰퍼드(German Shepherd)',
  '저먼 쇼트 헤어드 포인터(German Shorthaired Pointer)',
  '저먼 와이어 헤어드 포인터(German Wirehaired Pointer)',
  '일본 스피츠(Japanese Spitz)',
  '달마티안(Dalmatian)',
  '쿤하운드(Kooikerhondje)',
  '캉갈(Kangal)',
  '푸덴코 카나리오(Fodenco Canario)',
  '케언 테리어(Cairn Terrier)',
  '케리 블루 테리어(Kerry Blue Terrier)',
  '콜리(Collie)',
  '보더 콜리(Border Collie)',
  '비어디드 콜리(Bearded Collie)',
  '풀리(Puli)',
  '벨지안 타뷰렌(Belgian Tervuren)',
  '셰틀랜드 시프도그(Shetland Sheepdog)',
  '보르도 마스티프(Bordeaux Mastiff)',
  '마스티프(Mastiff)',
  '티베탄 마스티프(Tibetan Mastiff)',
  '보스롱(Boslong Mastiff)',
  '그레이트 데인(Great Dane)',
  '로트바일러(Rottweiler)',
  '불마스티프(Bullmastiff)',
  '복서(Boxer)',
  '도베르만 핀셔(Doberman Pinscher)',
  '비글(Beagle)',
  '래브라도 리트리버(Labrador Retriever)',
  '골든 리트리버(Golden Retriever)',
  '체서피크 베이 리트리버(Chesapeake Bay Retriever)',
  '컬리 코티드 리트리버(Curly Coated Retriever)',
  '플랫 코티드 리트리버(Flat Coated Retriever)',
  '사모예드(Samoyed)',
  '시베리안 허스키(Siberian Husky)',
  '그린란드 도그(Greenland Dog)',
  '캐나디안 에스키모 도그(Canadian Eskimo Dog)',
  '치누크(Chinook)',
  '래브라도 허스키(Labrador Husky)',
  '맥켄지 강 허스키(Mackenzie River Husky)',
  '노던 이누이트 도그(Northern Inuit Dog)',
  '사할린 허스키(Sakhalin Husky)',
  '세팔라 시베리안(Seppala Siberian)',
  '타마스칸(Tamaskan Dog)',
  '세인트 버나드(Saint Bernard)',
  '버니즈 마운틴(Bernese Mountain Dog)',
  '도그 부비에 데 플랑드르(Bouvier des Flandres)',
  '뉴펀들랜드(Newfoundland)',
  '포메라니안(Pomeranian)',
  '퍼그(Pug)',
  '페키니즈(Pekingese)',
  '차우차우(Chow Chow)',
  '시바견(Shiba Inu)',
  '도사견(Dosa Dog)',
  '삽살개(Sapsal Dog)',
  '제주개(Jeju Dog)',
  '진돗개(Jindo Dog)',
  '통일개(Tongil Dog)',
  '풍산개(Pungsan Dog)',
  '친(Chin)',
  '말티즈(Maltese)',
  '일본 테리어(Japanese Terrier)',
  '토이 맨체스터 테리어(Toy Manchester Terrier)',
  '파피용(Papillon)',
  '차이니스 크레스티드(Chinese Crested)',
  '미니어처 핀셔(Miniature Pinscher)',
  '토이 푸들(Toy Poodle)',
  '스탠더드 푸들(Standard Poodle)',
  '미니어처 푸들(Miniature Poodle)',
  '실리햄 테리어(Sealyham Terrier)',
  '베들링턴 테리어(Bedlington Terrier)',
  '노리치 테리어(Norwich Terrier)',
  '맨체스터 테리어(Manchester Terrier)',
  '폭스 테리어(Fox Terrier)',
  '웰시 테리어(Welsh Terrier)',
  '스태퍼드셔 불 테리어(Staffordshire Bull Terrier)',
  '불 테리어(Bull Terrier)',
  '댄디 딘몬트 테리어(Dandie Dinmont Terrier)',
  '미니어처 슈나우저(Miniature Schnauzer)',
  '스코티시 테리어(Scottish Terrier)',
  '오스트레일리안 테리어(Australian Terrier)',
  '티베탄 테리어(Tibetan Terrier)',
  '티베탄 스패니얼(Tibetan Spaniel)',
  '라사압소(Lhasa Apso)',
  '프렌치 불도그(French Bulldog)',
  '보스턴 테리어(Boston Terrier)',
  '스키퍼키(Skye Terrier)',
  '키스혼드(Keeshond)',
  '불도그(Bulldog)',
  '비숑 프리제(Bichon Frise)',
  '독일 스피츠(German Spitz)',
  '실키 테리어(Silky Terrier)',
  '브뤼셀 그리폰(Brussels Griffon)',
  '킹 찰스 스패니얼(King Charles Spaniel)',
  '카발리에 킹 찰스 스패니얼(Cavalier King Charles Spaniel)',
  '믹스견(Mixed Breed)',
];

export const catBreeds: string[] = [
  '아나톨리(Anatolian)',
  '아라비안 마우(Arabian Mau)',
  '아비시니안(Abyssinian)',
  '아메리칸 링테일(American Ringtail)',
  '아메리칸 컬(American Curl)',
  '아메리칸 쇼트헤어(American Shorthair)',
  '아메리칸 와이어헤어(American Wirehair)',
  '아시안(Asian)',
  '아즈레스 오호스(Azores Ohos)',
  '라가머핀(Ragamuffin)',
  '라펌(Rafum)',
  '라아스(Raas)',
  '램킨(Lambkin)',
  '라코이(Lykoi)',
  '라벤더(Lavender)',
  '발리니즈(Balinese)',
  '바레인 딜문(Bahrain Dilmun)',
  '밤비노(Bambino)',
  '뱅갈(Bengal)',
  '브램블(Bramble)',
  '브라질리안 쇼트헤어(Brazilian Shorthair)',
  '브리티시 롱헤어(British Longhair)',
  '브리티시 쇼트헤어(British Shorthair)',
  '버먼(Birman)',
  '버밀라(Burmilla)',
  '봄베이(Bombay)',
  '버미즈(Burmese)',
  '카렐리안 밥테일(Karelian Bobtail)',
  '카오 마니(Khao Manee)',
  '캘리포니아 스팽글드(California Spangled)',
  '카슈미르(Kashmir)',
  '키프로스(Cyprus)',
  '키프로스 아프로디테(Cyprus Aphrodite)',
  '킨카로우(Kinkalow)',
  '코니시 렉스(Cornish Rex)',
  '코호나(Kohona)',
  '코랏(Korat)',
  '쿠릴리안 밥테일(Kurilian Bobtail)',
  '켈라스 고양이(Kellas Cat)',
  '콘 자(Konja)',
  '데본 렉스(Devon Rex)',
  '돈스코이(Donskoy)',
  '드래곤 리(Dragon Li)',
  '드웰프(Dwelf)',
  '라펌(Rafum)',
  '라가머핀(Ragamuffin)',
  '라아스(Raas)',
  '라코이(Lykoi)',
  '라벤더(Lavender)',
  '라가머핀(Ragamuffin)',
  '만달레이(Mandalay)',
  '말레이시아(Malaysian Cat)',
  '메인쿤(Maine Coon)',
  '맹크스(Manx)',
  '민스킨(Minskin)',
  '미뉴에트(Minuet)',
  '모하비 밥(Mojave Bob)',
  '모하비 점무늬(Mojave Spotted)',
  '뉴질랜드(New Zealand)',
  '네벨룽(Nebelung)',
  '네팔라얀(Nepalayan)',
  '네바마스커레이드(Nevamasquerade)',
  '노르웨이 숲(Norwegian Forest Cat)',
  '오스트레일리안 미스트(Australian Mist)',
  '오스트레일리안 티파니(Australian Tiffany)',
  '오리엔탈 바이컬러(Oriental Bicolor)',
  '오리엔탈 롱헤어(Oriental Longhair)',
  '오리엔탈 쇼트헤어(Oriental Shorthair)',
  '오위히 밥(Owyhee Bob)',
  '오시캣(Ocicat)',
  '오리건 렉스(Oregon Rex)',
  '우랄 렉스(Ural Rex)',
  '우수리(Ussuri)',
  '유러피안 쇼트헤어(European Shorthair)',
  '유크레이니언 레브코이(Ukrainian Levkoy)',
  '엠프(Elf)',
  '재그(Zag)',
  '재패니즈 밥테일(Japanese Bobtail)',
  '자바니즈(Javanese)',
  '세이셸(Seychelles)',
  '세일론(Ceylon)',
  '세라데 쁘띠(Serade Petit)',
  '샴(Siamese)',
  '샘 사웨트(Sam Sawet)',
  '샤르트뢰(Chartreux)',
  '샹틸리 티파니(Chantilly Tiffany)',
  '시벨라(Sibella)',
  '시베리안(Siberian)',
  '싱가푸라(Singapura)',
  '스노우슈(Snowshoe)',
  '소말리(Somali)',
  '소코케(Sokoke)',
  '스쿠쿰(Skookum)',
  '스핑크스(Sphynx)',
  '타이(Thai)',
  '테네시 렉스(Tennessee Rex)',
  '통키니즈(Tonkinesse)',
  '토이 밥(Toy Bob)',
  '토이거(Toyger)',
  '토이 푸들(Toy Poodle)',
  '폴덱스(Poldex)',
  '페르시안(Persian)',
  '페르시안 친칠라(Persian Chinchilla)',
  '피터볼드(Peterbald)',
  '픽시 밥(Pixie Bob)',
  '포린 화이트(Foreign White)',
  '프렌치 불도그(French Bulldog)',
  '랙돌(Ragdoll)',
  '라가머핀(Ragamuffin)',
  '엘프(Elf)',
  '하바나 브라운(Havana Brown)',
  '하일랜더(Highlander)',
  '팬서렛(Pantheret)',
  '사바나(Savannah)',
  '세렝게티(Serengeti)',
  '치토(Chito)',
  '정글밥(Jungle Bob)',
  '사파리(Safari)',
  '브램블(Bramble)',
  '재그(Zag)',
  '모하비 밥(Mojave Bob)',
  '모하비 점무늬(Mojave Spotted)',
  '네팔라얀(Nepalayan)',
  '믹스견(Mixed Breed)',
];
export const formatDogBreeds = (breeds: string[]) => {
  return breeds.map((breed) => {
    const value = breed
      .replace(/\(.+\)/, '') // 괄호 안 영문 제거
      .trim()
      .toLowerCase();
    return { value, label: breed };
  });
};
