import { AnimalGender, AnimalType } from '@/entities/animal/animal';
import type { AnimalListItem } from '@/entities/animal/animal-api';

export const dummyAnimals: AnimalListItem[] = [
  {
    id: 'a1',
    name: '코코',
    type: AnimalType.DOG,
    gender: AnimalGender.FEMALE,
    breed: '푸들',
    birth_date: new Date('2020-05-12'),
    image: '/images/animal01.jpg',
    euthanasia_date: null,
    isEmergency: false,
  },
  {
    id: 'a2',
    name: '보리',
    type: AnimalType.CAT,
    gender: AnimalGender.MALE,
    breed: '러시안블루',
    birth_date: new Date('2021-11-02'),
    image: '/images/animal02.jpg',
    euthanasia_date: null,
    isEmergency: true,
  },
  {
    id: 'a3',
    name: '몽이',
    type: AnimalType.DOG,
    gender: AnimalGender.MALE,
    breed: '말티즈',
    birth_date: new Date('2019-09-15'),
    image: '/images/animal03.jpg',
    euthanasia_date: null,
    isEmergency: false,
  },
  {
    id: 'a4',
    name: '하루',
    type: AnimalType.CAT,
    gender: AnimalGender.FEMALE,
    breed: '페르시안',
    birth_date: new Date('2022-03-08'),
    image: '/images/animal01.jpg',
    euthanasia_date: null,
    isEmergency: false,
  },
  {
    id: 'a5',
    name: '초코',
    type: AnimalType.DOG,
    gender: AnimalGender.MALE,
    breed: '시츄',
    birth_date: new Date('2018-12-30'),
    image: '/images/animal02.jpg',
    euthanasia_date: null,
    isEmergency: true,
  },
  {
    id: 'a6',
    name: '냥이',
    type: AnimalType.CAT,
    gender: AnimalGender.FEMALE,
    breed: '코리안숏헤어',
    birth_date: new Date('2020-01-20'),
    image: '/images/animal03.jpg',
    euthanasia_date: null,
    isEmergency: false,
  },
  {
    id: 'a7',
    name: '두리',
    type: AnimalType.DOG,
    gender: AnimalGender.FEMALE,
    breed: '골든리트리버',
    birth_date: new Date('2017-07-11'),
    image: '/images/animal01.jpg',
    euthanasia_date: null,
    isEmergency: false,
  },
  {
    id: 'a8',
    name: '루이',
    type: AnimalType.DOG,
    gender: AnimalGender.MALE,
    breed: '비숑 프리제',
    birth_date: new Date('2021-04-04'),
    image: '/images/animal02.jpg',
    euthanasia_date: null,
    isEmergency: true,
  },
  {
    id: 'a9',
    name: '하늘',
    type: AnimalType.CAT,
    gender: AnimalGender.FEMALE,
    breed: '샴',
    birth_date: new Date('2019-06-25'),
    image: '/images/animal03.jpg',
    euthanasia_date: null,
    isEmergency: false,
  },
  {
    id: 'a10',
    name: '감자',
    type: AnimalType.DOG,
    gender: AnimalGender.MALE,
    breed: '믹스',
    birth_date: new Date('2023-02-10'),
    image: '/images/animal01.jpg',
    euthanasia_date: null,
    isEmergency: true,
  },
];
