/* eslint-disable @next/next/no-css-tags */
import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import TopBar from '@/shared/widgets/navigation/top-bar';
import { Toaster } from '@/shared/ui/sonner';
import BottomBar from '@/shared/widgets/navigation/bottom-bar';

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: '임시보호 매칭 플랫폼 퍼디즈',
  description: 'Generated by rositechcompany',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          href="//fonts.googleapis.com/earlyaccess/nanumpenscript.css"
        />
      </head>
      <body className={pretendard.className}>
        <div className="flex min-h-screen flex-col">
          <TopBar />
          <div className="flex-1">{children}</div>
          <Toaster />
          <BottomBar />
        </div>
      </body>
    </html>
  );
}
