import type { Metadata } from 'next';
import './globals.css';
import localFont from 'next/font/local';
import Script from 'next/script';
import { Toaster } from '@/components/ui/sonner';
import TopBar from '@/components/common/top-bar';
import BottomBar from '@/components/common/bottom-bar';

declare global {
  interface Window {
    kakao: Record<string, unknown>;
  }
}

const pretendard = localFont({
  src: '../../public/fonts/PretendardVariable.woff2',
  display: 'swap',
  weight: '45 920',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: '임시보호 매칭 플랫폼 퍼디',
  description: 'Generated by rositechcompany',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <Script src="https://cdn.iamport.kr/v1/iamport.js" />
        <Script src="//t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js" />
        <Script
          strategy="beforeInteractive"
          src={`//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_MAP_KEY}&autoload=false&libraries=services,clusterer,drawing`}
        />
      </head>
      <body className={`${pretendard.className}`}>
        <TopBar />
        <main>{children}</main>
        <Toaster />
        <BottomBar />
      </body>
    </html>
  );
}
