import { promises as fs } from 'fs';
import * as path from 'path';

import openapiTS, { astToString } from 'openapi-typescript';

const ROOT_DIR = path.resolve(__dirname, '..', '..');
const SPEC_PATH = path.resolve(ROOT_DIR, 'openapi', 'pet-openapi.json');
const OUTPUT_PATH = path.resolve(
  __dirname,
  '../src/shared/api/generated/pet-schema.ts',
);

async function generateTypes() {
  try {
    const schema = await fs.readFile(SPEC_PATH, 'utf-8');
    const ast = await openapiTS(JSON.parse(schema));
    const content = astToString(ast);

    await fs.mkdir(path.dirname(OUTPUT_PATH), { recursive: true });
    const header =
      '// This file is automatically generated by scripts/generate-openapi-types.ts\n' +
      '// Do not edit manually.\n\n';

    await fs.writeFile(
      OUTPUT_PATH,
      `${header}${content}`,
      'utf-8',
    );

    // eslint-disable-next-line no-console
    console.log(`Generated OpenAPI types at ${OUTPUT_PATH}`);
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('Failed to generate OpenAPI types', error);
    process.exitCode = 1;
  }
}

void generateTypes();
